### ISSUE TITLE
Doesn't work with Webstorm 12

### ISSUE THREAD

**Issue by davidmoshal** [henjue/vue-for-idea#12]
<img width="732" alt="screen shot 2016-02-01 at 2 08 26 pm" src="https://cloud.githubusercontent.com/assets/650245/12733086/9531f726-c8ed-11e5-8973-63d54200bff2.png">

**Comment by davidmoshal** [comment]
also doesnt work with Intellij 16

**Comment by DarkaOnLine** [comment]
+1

**Comment by forstjiri** [comment]
PHPStorm 11, same issue.

**Comment by ghost** [comment]
Appears to the same issue as #9

**Comment by catmeme** [comment]
Same Issue PyCharm 5.0.4

**Comment by ropeladder** [comment]
I'm having the same problem with WebStorm 10.0.4.

**Comment by springeye** [comment]
i will modified Kotlin language code into Java

**Comment by mikebronner** [comment]
Adding myself here to get notified. Would love to see this work in PHPStorm 11. :) Thanks!

**Comment by springeye** [comment]
@davidmoshal  please test https://github.com/henjue/vue-for-idea/blob/develop/src/main/vue-for-idea.jar

**Comment by davidmoshal** [comment]
Thanks, but I actually went in a different direction, had a deadline.
Will review once this project is done.

**Comment by agileago** [comment]
+1   报错

**Comment by ghost** [comment]
The downloaded jar file works with PyCharm 5.0.4 so I am closing #9 .

**Comment by JoshZA** [comment]
This works with 12 EAP now

**Comment by mikebronner** [comment]
Getting the following error in PHPStorm 11 EAP:

```
Component name collision: VueProjectSettingsComponent class io.j99.idea.vue.component.VueComponent and class io.j99.idea.vue.component.VueProjectSettingsComponent
java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:127)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:453)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.access$300(ComponentManagerImpl.java:52)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:513)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:123)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:107)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:90)
    at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:282)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:231)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.access$300(ProjectManagerImpl.java:68)
    at com.intellij.openapi.project.impl.ProjectManagerImpl$8.compute(ProjectManagerImpl.java:531)
    at com.intellij.openapi.project.impl.ProjectManagerImpl$8.compute(ProjectManagerImpl.java:527)
    at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:198)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
    at com.intellij.openapi.progress.impl.CoreProgressManager$8.run(CoreProgressManager.java:357)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.application.impl.ApplicationImpl$13$1.run(ApplicationImpl.java:633)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```
