### ISSUE TITLE
Creating a new project failed

### ISSUE THREAD

**Issue by bhulsman** [henjue/vue-for-idea#17]
I'm getting the error below, when clickin on 'File' -> 'New project...'.

```
@NotNull method io/j99/idea/vue/module/VueProjectGenerator.getName must not return null
java.lang.IllegalStateException: @NotNull method io/j99/idea/vue/module/VueProjectGenerator.getName must not return null
    at io.j99.idea.vue.module.VueProjectGenerator.getName(VueProjectGenerator.java:26)
    at com.intellij.ide.util.projectWizard.ProjectSettingsStepBase.<init>(ProjectSettingsStepBase.java:62)
    at com.jetbrains.php.actions.PhpStormProjectSpecificSettingsStep.<init>(PhpStormProjectSpecificSettingsStep.java:16)
    at com.jetbrains.php.actions.PhpStormNewProjectStep$Customization.createProjectSpecificSettingsStep(PhpStormNewProjectStep.java:42)
    at com.intellij.ide.util.projectWizard.AbstractNewProjectStep$Customization.getActions(AbstractNewProjectStep.java:82)
    at com.intellij.ide.util.projectWizard.AbstractNewProjectStep.<init>(AbstractNewProjectStep.java:51)
    at com.jetbrains.php.actions.PhpStormNewProjectStep.<init>(PhpStormNewProjectStep.java:15)
    at com.jetbrains.php.actions.PhpStormNewProjectAction$1.createRootStep(PhpStormNewProjectAction.java:13)
    at com.intellij.ide.util.projectWizard.AbstractNewProjectDialog.createCenterPanel(AbstractNewProjectDialog.java:54)
    at com.intellij.openapi.ui.DialogWrapper.init(DialogWrapper.java:1257)
    at com.intellij.ide.util.projectWizard.AbstractNewProjectDialog.<init>(AbstractNewProjectDialog.java:46)
    at com.jetbrains.php.actions.PhpStormNewProjectAction$1.<init>(PhpStormNewProjectAction.java:10)
    at com.jetbrains.php.actions.PhpStormNewProjectAction.actionPerformed(PhpStormNewProjectAction.java:10)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:311)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
    at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:281)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
    at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:513)
    at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:45)
    at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:533)
    at java.awt.Component.processMouseEvent(Component.java:6525)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6290)
    at java.awt.Container.processEvent(Container.java:2234)
    at java.awt.Component.dispatchEventImpl(Component.java:4881)
    at java.awt.Container.dispatchEventImpl(Container.java:2292)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
    at java.awt.Container.dispatchEventImpl(Container.java:2278)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:866)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by springeye** [comment]
@bhulsman If you did not enter a project name

**Comment by bhulsman** [comment]
No, I didn't get that far! When I'm in an existing (other) project, I click File -> Create new project; it should prompt for project location and other details, but I get this error and not the window. I had to disable the plugin to be able to create new a (non-vue related) project.

**Comment by whitelynx** [comment]
I've also gotten this error when opening an _existing_ project: https://youtrack.jetbrains.com/issue/WEB-20983

The strange thing is that it usually opens fine, but twice now it's failed with that error.

**Comment by springeye** [comment]
@whitelynx @bhulsman Yesterday, I checked the code found in the wrong place code is not used. In order to ensure the correct person, yesterday I reported the wrong code deleted (though not used)，The next version should not appear this problem，close this issues???

**Comment by bhulsman** [comment]
Are you trying to say it's an issue in PhpStorm/etc. and not in your plugin?

**Comment by mtio** [comment]
+1 I am getting the same issue.

**Comment by springeye** [comment]
@bhulsman  Recently I will release a version, rest a lot of problems, trouble you to try again

**Comment by wangchenhao** [comment]
使用的是webstorm 2016.1 安装了插件以后也出现  File -> Create new project 会报错的问题。

**Comment by antoniopaisfernandes** [comment]
+1

**Comment by phtwo** [comment]
me too

**Comment by springeye** [comment]
please update to 1.0.5
