### ISSUE TITLE
@NotNull method io/j99/idea/vue/module/VueProjectGenerator.getName must not return null

### ISSUE THREAD

**Issue by daglob** [henjue/vue-for-idea#23]
@NotNull method io/j99/idea/vue/module/VueProjectGenerator.getName must not return null
java.lang.IllegalStateException: @NotNull method io/j99/idea/vue/module/VueProjectGenerator.getName must not return null
    at io.j99.idea.vue.module.VueProjectGenerator.getName(VueProjectGenerator.java:26)
    at com.intellij.ide.util.projectWizard.ProjectSettingsStepBase.<init>(ProjectSettingsStepBase.java:62)
    at com.jetbrains.php.actions.PhpStormProjectSpecificSettingsStep.<init>(PhpStormProjectSpecificSettingsStep.java:16)
    at com.jetbrains.php.actions.PhpStormNewProjectStep$Customization.createProjectSpecificSettingsStep(PhpStormNewProjectStep.java:42)
    at com.intellij.ide.util.projectWizard.AbstractNewProjectStep$Customization.getActions(AbstractNewProjectStep.java:82)
    at com.intellij.ide.util.projectWizard.AbstractNewProjectStep.<init>(AbstractNewProjectStep.java:51)
    at com.jetbrains.php.actions.PhpStormNewProjectStep.<init>(PhpStormNewProjectStep.java:15)
    at com.jetbrains.php.actions.PhpStormNewProjectAction$1.createRootStep(PhpStormNewProjectAction.java:13)
    at com.intellij.ide.util.projectWizard.AbstractNewProjectDialog.createCenterPanel(AbstractNewProjectDialog.java:54)
    at com.intellij.openapi.ui.DialogWrapper.init(DialogWrapper.java:1257)
    at com.intellij.ide.util.projectWizard.AbstractNewProjectDialog.<init>(AbstractNewProjectDialog.java:46)
    at com.jetbrains.php.actions.PhpStormNewProjectAction$1.<init>(PhpStormNewProjectAction.java:10)
    at com.jetbrains.php.actions.PhpStormNewProjectAction.actionPerformed(PhpStormNewProjectAction.java:10)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:311)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
    at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:281)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
    at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:513)
    at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:45)
    at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:533)
    at java.awt.Component.processMouseEvent(Component.java:6535)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6300)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4891)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:866)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

PS: 
PhpStorm 10.0.3 build PS-143.1770
JRE: 1.8.0_65-b17 amd64

**Comment by asalisbury** [comment]
Upon upgrading PhpStorm to 2016.1 I began having a similar issue.

As indicated by this part of the stack trace:

```
Caused by: java.lang.IllegalStateException: @NotNull method io/j99/idea/vue/module/VueProjectGenerator.getName must not return null
    at io.j99.idea.vue.module.VueProjectGenerator.getName(VueProjectGenerator.java:26)
    at com.intellij.ide.util.projectWizard.ProjectSettingsStepBase.<init>(ProjectSettingsStepBase.java:62)
    at com.jetbrains.php.actions.PhpStormProjectSpecificSettingsStep.<init>(PhpStormProjectSpecificSettingsStep.java:16)
    at com.jetbrains.php.actions.PhpStormNewProjectStep$Customization.createProjectSpecificSettingsStep(PhpStormNewProjectStep.java:42)
    at com.intellij.ide.util.projectWizard.AbstractNewProjectStep$Customization.getActions(AbstractNewProjectStep.java:112)
    at com.intellij.ide.util.projectWizard.AbstractNewProjectStep$Customization.getActions(AbstractNewProjectStep.java:99)
    at com.intellij.ide.util.projectWizard.AbstractNewProjectStep.<init>(AbstractNewProjectStep.java:65)
    at com.jetbrains.php.actions.PhpStormNewProjectStep.<init>(PhpStormNewProjectStep.java:15)
    ... 22 more
```

(for PhpStorm 2016.1 Build #PS-145.258, built on March 16, 2016, though similar issue after upgrading to WebStorm 2016.1)

**Comment by caryxiao** [comment]
+1 
![image](https://cloud.githubusercontent.com/assets/2449891/13870174/e01656f4-ed16-11e5-8967-5e0c218c5d8f.png)

**Comment by luwenjin** [comment]
+1

**Comment by forcszhangguoyu** [comment]
+1

**Comment by marcusmoore** [comment]
Same for me. Interesting because it's working on my desktop but not my laptop. I'm not sure what is different between the two.

**Comment by springeye** [comment]
Sorry, how much is the plugin version?

**Comment by marcusmoore** [comment]
I manually removed the plugin from the plugin folder and restarted PHPStorm. It worked fine at this point (with the plugin removed).

Then I installed the plugin via the Plugin search within PHPStorm and when it restarted I get the same error.

I'm assuming it would be the latest version?

**Comment by forcszhangguoyu** [comment]
1.0.4, the latest version

**Comment by marcusmoore** [comment]
Just checked again. Yes. I'm installing 1.0.4. Here's something interesting...

I opened `~/Library/Application Support/PhpStorm2016.1` and noticed that when PHPStorm starts up it deletes and recreates an `extensions.xml` file. I think that the extension will fail out based on if this file is created before or after the extension is loaded...Sometimes PHPStorm will open ok. Other times it will fail immediately.

Here's an example of the last error I got:

```
Internal error. Please report to http://jb.gg/ide/critical-startup-errors

com.intellij.diagnostic.PluginException: cannot create class 'com.jetbrains.php.actions.PhpStormNewProjectStep' [Plugin: com.intellij]
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:194)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:166)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:511)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.a(ActionManagerImpl.java:491)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:484)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActions(ActionManagerImpl.java:1263)
    at com.intellij.openapi.actionSystem.impl.ActionPreloader.preload(ActionPreloader.java:31)
    at com.intellij.openapi.application.Preloader$2$1.run(Preloader.java:78)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.application.Preloader$2.run(Preloader.java:74)
    at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:187)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:520)
    at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:154)
    ... 16 more
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at com.intellij.util.ReflectionUtil.newInstance(ReflectionUtil.java:484)
    ... 17 more
Caused by: java.lang.IllegalStateException: @NotNull method io/j99/idea/vue/module/VueProjectGenerator.getName must not return null
    at io.j99.idea.vue.module.VueProjectGenerator.getName(VueProjectGenerator.java:26)
    at com.intellij.ide.util.projectWizard.ProjectSettingsStepBase.<init>(ProjectSettingsStepBase.java:62)
    at com.jetbrains.php.actions.PhpStormProjectSpecificSettingsStep.<init>(PhpStormProjectSpecificSettingsStep.java:16)
    at com.jetbrains.php.actions.PhpStormNewProjectStep$Customization.createProjectSpecificSettingsStep(PhpStormNewProjectStep.java:42)
    at com.intellij.ide.util.projectWizard.AbstractNewProjectStep$Customization.getActions(AbstractNewProjectStep.java:112)
    at com.intellij.ide.util.projectWizard.AbstractNewProjectStep$Customization.getActions(AbstractNewProjectStep.java:99)
    at com.intellij.ide.util.projectWizard.AbstractNewProjectStep.<init>(AbstractNewProjectStep.java:65)
    at com.jetbrains.php.actions.PhpStormNewProjectStep.<init>(PhpStormNewProjectStep.java:15)
    ... 22 more
```

**Comment by springeye** [comment]
see #17
