### ISSUE TITLE
Vue-for-idea conflict in Pycharm 2016.1: prevents New Project

### ISSUE THREAD

**Issue by mjmare** [henjue/vue-for-idea#25]
I found this plugin very useful when working with Vue (obviously). However after some time (ussually a day or so) after installing I get problems with PyCharm startup and/or starting a new project. Uninstalling en reinstalling fixes things for some time.   

`@NotNull method io/j99/idea/vue/module/VueProjectGenerator.getName must not return null
java.lang.IllegalStateException: @NotNull method io/j99/idea/vue/module/VueProjectGenerator.getName must not return null
    at io.j99.idea.vue.module.VueProjectGenerator.getName(VueProjectGenerator.java:26)
    at com.jetbrains.python.newProject.actions.PyCharmNewProjectStep$Customization$1.compare(PyCharmNewProjectStep.java:75)
    at com.jetbrains.python.newProject.actions.PyCharmNewProjectStep$Customization$1.compare(PyCharmNewProjectStep.java:70)
    at java.util.TimSort.countRunAndMakeAscending(TimSort.java:360)
    at java.util.TimSort.sort(TimSort.java:220)
    at java.util.Arrays.sort(Arrays.java:1438)
    at com.jetbrains.python.newProject.actions.PyCharmNewProjectStep$Customization.getProjectGenerators(PyCharmNewProjectStep.java:70)
    at com.intellij.ide.util.projectWizard.AbstractNewProjectStep.<init>(AbstractNewProjectStep.java:62)
    at com.jetbrains.python.newProject.actions.PyCharmNewProjectStep.<init>(PyCharmNewProjectStep.java:40)
    at com.jetbrains.python.newProject.PyCharmNewProjectDialog.createRootStep(PyCharmNewProjectDialog.java:24)
    at com.jetbrains.python.newProject.PyCharmNewProjectDialog.createRootStep(PyCharmNewProjectDialog.java:21)
    at com.intellij.ide.util.projectWizard.AbstractNewProjectDialog.createCenterPanel(AbstractNewProjectDialog.java:56)
    at com.intellij.openapi.ui.DialogWrapper.init(DialogWrapper.java:1280)
    at com.intellij.ide.util.projectWizard.AbstractNewProjectDialog.<init>(AbstractNewProjectDialog.java:48)
    at com.jetbrains.python.newProject.PyCharmNewProjectDialog.<init>(PyCharmNewProjectDialog.java:21)
    at com.jetbrains.python.newProject.PyCharmNewProjectAction.actionPerformed(PyCharmNewProjectAction.java:24)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:191)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:311)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
    at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:281)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308)
    at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
    at com.apple.laf.ScreenMenuItemCheckbox.itemStateChanged(ScreenMenuItemCheckbox.java:193)
    at java.awt.CheckboxMenuItem.processItemEvent(CheckboxMenuItem.java:389)
    at java.awt.CheckboxMenuItem.processEvent(CheckboxMenuItem.java:357)
    at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:351)
    at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:339)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:761)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at com.intellij.ide.IdeEventQueue.g(IdeEventQueue.java:857)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

**Comment by jariz** [comment]
Same here on PhpStorm 2016.1 with and without a configured vue-cli path :cry:
Crashes every time with the same error when I open the new project dialog, no matter how long ago I enabled the plugin (unlike OP said)
Real shame because the markup is still working great.

**Comment by JoshZA** [comment]
Same issue in Webstorm - this plugin also appears to cause the IDE caches to corrupt which causes a hang during startup

**Comment by springeye** [comment]
please update to 1.0.5
